// 环境变量读取（阶段 01 基础版；阶段 02+ 完善校验）
export interface WorkerEnv {
  REDIS_URL?: string;
  DATABASE_URL?: string;
  NODE_ENV?: string;
  FINANCEHOT_QUEUE_PREFIX?: string;
  FINANCEHOT_WORKER_CONCURRENCY?: string;
  FINANCEHOT_QUEUE_ATTEMPTS?: string;
  FINANCEHOT_QUEUE_BACKOFF_MS?: string;
  FINANCEHOT_KEEP_COMPLETED?: string;
  FINANCEHOT_KEEP_FAILED?: string;
  FINANCEHOT_SCHEDULER_INTERVAL_MS?: string;
  FINANCEHOT_SOURCE_LOCK_TTL_MS?: string;
  FINANCEHOT_DRAIN_TIMEOUT_MS?: string;
  FINANCEHOT_CLUSTER_SIMILARITY_THRESHOLD?: string;
  FINANCEHOT_CLUSTER_DIRECT_MERGE_THRESHOLD?: string;
  FINANCEHOT_CLUSTER_TITLE_FEATURE_THRESHOLD?: string;
  FINANCEHOT_CLUSTER_LLM_MIN_CONFIDENCE?: string;
  FINANCEHOT_CLUSTER_TIME_WINDOW_HOURS?: string;
}

export function loadEnv(): WorkerEnv {
  return {
    REDIS_URL: process.env.REDIS_URL,
    DATABASE_URL: process.env.DATABASE_URL,
    NODE_ENV: process.env.NODE_ENV,
    FINANCEHOT_QUEUE_PREFIX: process.env.FINANCEHOT_QUEUE_PREFIX,
    FINANCEHOT_WORKER_CONCURRENCY: process.env.FINANCEHOT_WORKER_CONCURRENCY,
    FINANCEHOT_QUEUE_ATTEMPTS: process.env.FINANCEHOT_QUEUE_ATTEMPTS,
    FINANCEHOT_QUEUE_BACKOFF_MS: process.env.FINANCEHOT_QUEUE_BACKOFF_MS,
    FINANCEHOT_KEEP_COMPLETED: process.env.FINANCEHOT_KEEP_COMPLETED,
    FINANCEHOT_KEEP_FAILED: process.env.FINANCEHOT_KEEP_FAILED,
    FINANCEHOT_SCHEDULER_INTERVAL_MS: process.env.FINANCEHOT_SCHEDULER_INTERVAL_MS,
    FINANCEHOT_SOURCE_LOCK_TTL_MS: process.env.FINANCEHOT_SOURCE_LOCK_TTL_MS,
    FINANCEHOT_DRAIN_TIMEOUT_MS: process.env.FINANCEHOT_DRAIN_TIMEOUT_MS,
    FINANCEHOT_CLUSTER_SIMILARITY_THRESHOLD: process.env.FINANCEHOT_CLUSTER_SIMILARITY_THRESHOLD,
    FINANCEHOT_CLUSTER_DIRECT_MERGE_THRESHOLD: process.env.FINANCEHOT_CLUSTER_DIRECT_MERGE_THRESHOLD,
    FINANCEHOT_CLUSTER_TITLE_FEATURE_THRESHOLD: process.env.FINANCEHOT_CLUSTER_TITLE_FEATURE_THRESHOLD,
    FINANCEHOT_CLUSTER_LLM_MIN_CONFIDENCE: process.env.FINANCEHOT_CLUSTER_LLM_MIN_CONFIDENCE,
    FINANCEHOT_CLUSTER_TIME_WINDOW_HOURS: process.env.FINANCEHOT_CLUSTER_TIME_WINDOW_HOURS,
  };
}
